name: CI Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Run ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - run: npm ci
            - run: npm run lint

    test:
        name: Run Jest Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - run: npm ci
            - run: npm run test -- --ci

    build:
        name: Run Production Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - run: npm ci
            - run: npm run build
